### ISSUE TITLE
月份和日期变化的时候，引起了年份的变化

### ISSUE THREAD

**Issue by dillon-cupider** [xfhxbb/LCalendar#1]
我设置了 data-lcalendar="2011-01-11,2016-12-31" 
画面年份选择2014年，这个时候月份从11变12，这个时候年就会变成2013
一下几种情况都会出现年份变化的现象
1，月份选择1月，手势从上往下
2，月份选择12月，手势从下玩上
3，日期选择1号，手势从上往下
4，日期选择该月份的最后一日，手势从下往上

**Comment by dillon-cupider** [comment]
是不是把第291行代码
date_yy.setAttribute("top", yyVal);
改成
date_yy.setAttribute("val", yyVal);
就行了？

**Comment by xfhxbb** [comment]
是的，太感谢了，top的赋值都是copy的，所以一多就覆盖了val的赋值了，感谢感谢！
