### ISSUE TITLE
datetime 的情况下字体会变大

### ISSUE THREAD

**Issue by RyanPro** [xfhxbb/LCalendar#11]
使用date字体正常，datetime字体会变大。
和swiper会有一些兼容问题，比如z-index设置的过小导致弹出框出不来

**Comment by leftmouse** [comment]
css处的.gearDate增加一个.gearDatetime变成.gearDatetime,.gearDate

**Comment by laojin1105** [comment]
是的，我也发现这个问题了。datetime时字体变大重叠到一起了

**Comment by xfhxbb** [comment]
css样式少写了一个类，已修复
