### ISSUE TITLE
选择日期时双击日期，页面显示NaN

### ISSUE THREAD

**Issue by linuxKang** [xfhxbb/LCalendar#24]
如果在控件中双击年份、月份等位置，选择完成后时间会变成NaN，求楼主解决。谢谢

**Comment by li9269391** [comment]
https://github.com/xfhxbb/LCalendar/pull/10

**Comment by sunnychyy** [comment]
我也出现这个问题了

**Comment by xfhxbb** [comment]
> 如果在控件中双击年份，月份等位置，选择完成后时间会变成NaN的，求楼主解决谢谢。

1.80版已修复
