### ISSUE TITLE
LCalender插件报错

### ISSUE THREAD

**Issue by xumqfaith** [xfhxbb/LCalendar#33]
一直报错：Uncaught TypeError: Cannot read property 'querySelector' of null，
找不到原因，请作者帮忙

**Comment by xumqfaith** [comment]
滑动年和月没有问题，只要滑动日期就报错，bug,bug

**Comment by loiee** [comment]
在大概552行 `target["int_" + target.id] = setInterval(function() {` 这段代码下面加上`                    if(!_self.gearDate){
                        clearInterval(target["int_" + target.id]);
                        return;
                    }`

**Comment by xfhxbb** [comment]
1.80版本已解决
