### ISSUE TITLE
博主。 这个应该怎么让他同时适配页面端和移动端？

### ISSUE THREAD

**Issue by linguangyu** [xfhxbb/LCalendar#36]
博主。 这个应该怎么让他同时适配页面端和移动端？

**Comment by duck-zqd** [comment]
请问群主，我也想问一下这个问题，将样式改成rem后选择日期哪里就会出现选的日期的值跟实际的值不符

**Comment by zhangdaren** [comment]
加10086呀，，源码里是用的em。

**Comment by zhangdaren** [comment]
经过一番调试，已经可以支持移动端rem单位了，详情查看源码：
https://github.com/zhangdaren/lCalendar

**Comment by xfhxbb** [comment]
建议页面直接换别的插件使用哦
