### ISSUE TITLE
怎么获取日期的值？

### ISSUE THREAD

**Issue by Zoe-0820** [xfhxbb/LCalendar#41]
选择了日期之后，我要怎么获取value？
看到之前有人提出来了，但是小白表示看不懂啊/(ㄒoㄒ)/~~
求方法简明的解析？

**Comment by kikyzhanglihui** [comment]
1、在init方法中，追加closeFn参数；
`init: function(params) {
.....
            this.closeFn = params.closeFn;
        }`
2、在取消函数中执行closeFn，并将表单元素作为参数传递给该方法；
`//取消
            function closeMobileCalendar(e) {
......
              typeof _self.closeFn === 'function' && _self.closeFn( _self.trigger);
            }`

3、在实例化调用时定义closeFn，操作表单元素获取值
` var calendar = new LCalendar();
                calendar.init({
                    'trigger': '.datepicker',
                    'type': 'ym',
                    'minDate': '1900-1',
                    'maxDate': new Date().getFullYear() + '-' + (new Date().getMonth() + 1) ,
                    'closeFn': function(oInput){
                        alert(oInput.value)
                   }
                });`

**Comment by yudaren007007** [comment]
https://github.com/yudaren007007/qz-calendar 修改了一下，简单粗暴直接获取input.value就能取到值

**Comment by yancongwen** [comment]
你们都搞那么复杂干嘛？直接监听input事件就好了嘛
```
document.getElementById('你的id').addEventListener('input', e => {
  console.log(e.target.value)
})
```

**Comment by xfhxbb** [comment]
document.querySelector('#demo1').value
