### ISSUE TITLE
当点击input触发时间控件时，不滚动控件，直接点击月和日的位置，再点击返回，值会变为val="NaN"  top="NaNem"，请麻烦帮忙解决更新一下

### ISSUE THREAD

**Issue by dhj2020** [xfhxbb/LCalendar#43]
当点击input触发时间控件时，不滚动控件，直接点击月和日的位置，再点击返回，值会变为val="NaN"  top="NaNem"，请麻烦帮忙解决更新一下

![Uploading 02.png…]()

**Comment by yylww** [comment]
541行
<pre>var flag = (target["new_" + target.id] - target["old_" + target.id]) / (target["n_t_" + target.id] - target["o_t_" + target.id]);</pre>
改为
<pre>var flag = (target["new_" + target.id] - target["old_" + target.id]) / (target["n_t_" + target.id] - target["o_t_" + target.id]) || 0;</pre>
具体为啥，我也不清楚，只知道出现NaN是  flag值为NaN时导致的，所以加了个默认值0就好了

**Comment by sugarrain** [comment]
在setGear方法里面加一行if(val !== val) return 就可以解决了

**Comment by xfhxbb** [comment]
1.80版本已解决
