### ISSUE TITLE
有一个很尴尬的bug

### ISSUE THREAD

**Issue by polkYu** [xfhxbb/LCalendar#45]

**Comment by polkYu** [comment]
如果设置日期范围2017-9-18到2017-9-25（就是日子数不满一个月），选择会出bug····有什么解决办法吗

**Comment by polkYu** [comment]
更新：发现不是不满一个月会出bug，而是没有1号的选项会选择出bug·······

**Comment by polkYu** [comment]
日期范围太小也会出bug，求解决方法

**Comment by yudaren007007** [comment]
https://github.com/yudaren007007/qz-calendar 修复啦啦啦，留个start再走！

**Comment by xfhxbb** [comment]
> 日期范围太小也会出错误，求解决方法

请尝试一下1.80版本
