### ISSUE TITLE
重置日期节点个数时，死循环，报错

### ISSUE THREAD

**Issue by Hotinly** [xfhxbb/LCalendar#51]
`//重置日期节点个数`
https://github.com/xfhxbb/LCalendar/blob/38832129f6f64078fe14752f8cd3e02b7d6c2b1a/src/js/LCalendar.js#L332
如果日期选择控件还处于滚动状态(**没有完全定位到具体的日期上**)，此时点击了**确定按钮**，则此时会进入一个死循环，此处会一直报错：
　　　　　　　　　　　`Uncaught TypeError: Cannot read property 'querySelector' of null`
**需加上一个为空判断**  `if(!_self.gearDate){return;}`

**Comment by justinbaby** [comment]
NICE

**Comment by justinbaby** [comment]
THANK U

**Comment by hopegame** [comment]
1.71版本还没有修复这个.需要自己加~

**Comment by xfhxbb** [comment]
新版本已修复
