### ISSUE TITLE
建议放个外观DEMO

### ISSUE THREAD

**Issue by fangxianzheng** [xfhxbb/LCalendar#6]
哪怕截图也好啊

**Comment by liugonghe** [comment]
![image](https://cloud.githubusercontent.com/assets/27138450/25978614/e3bc1828-36f5-11e7-8c33-5cb60938bf36.png)

**Comment by xfhxbb** [comment]
有体验地址了https://xfhxbb.github.io/LCalendar/public/html/index.html
