### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by zhangqf** [xfhxbb/LCalendar#60]
Uncaught TypeError: Cannot read property 'querySelector' of null
    at setDateGearTooth (LCalendar.js:332)
    at setGear (LCalendar.js:668)
    at LCalendar.js:574
setDateGearTooth @ LCalendar.js:332
setGear @ LCalendar.js:668
(anonymous) @ LCalendar.js:574
setInterval (async)
rollGear @ LCalendar.js:552
gearTouchEnd @ LCalendar.js:539
日期选择特效这个input  中  多次选择日期 通常就会有这个报错

**Comment by sainwind** [comment]
meto

**Comment by xfhxbb** [comment]
请关注1.80版本
