### ISSUE TITLE
在苹果手机上不能正常显示，在有些安卓手机的微信浏览器上调不了日历插件

### ISSUE THREAD

**Issue by biaochenxuying** [xfhxbb/LCalendar#67]
大神，你好。
插件存在没大的兼容性问题啊。
在苹果手机上不能正常显示，在有些小米安卓手机的微信浏览器上调不了日历插件啊。

**Comment by biaochenxuying** [comment]
我找到原因了，是 index.html 里面的关于 body 的样式 overflow-x: hidden; 影响了的，去掉这句代码之后，苹果与安卓上都正常了。

**Comment by xfhxbb** [comment]
min-height是基于父元素的，这里我写的有问题，html作为顶级标签，需要给一个固定值height:100%而不是min-height: 100%
