### ISSUE TITLE
设置最小日期为下个月，就会出现时间选择在12月份的情况

### ISSUE THREAD

**Issue by leepule** [xfhxbb/LCalendar#76]
![image](https://user-images.githubusercontent.com/16642691/79814738-a04be580-83b1-11ea-879a-5b85626d0fa5.png)
![image](https://user-images.githubusercontent.com/16642691/79814735-9d50f500-83b1-11ea-8687-69bfdc1d9854.png)

**Comment by xfhxbb** [comment]
感谢，2.1.1版本修复
