### ISSUE TITLE
时间选择会报错

### ISSUE THREAD

**Issue by freedomdebug** [xfhxbb/LCalendar#8]
![qq 20160726140743](https://cloud.githubusercontent.com/assets/7620476/17127730/634788b6-533a-11e6-9479-16fdd99ec089.jpg)

操作：选择时间》滚动各个选择项目》确定   

死循环报错

**Comment by freedomdebug** [comment]
![qq 20160726140743](https://cloud.githubusercontent.com/assets/7620476/17127771/d0be44f2-533a-11e6-92a9-bf710f7f9405.jpg)

谷歌浏览器 版本 51.0.2704.84 m

**Comment by li9269391** [comment]
https://github.com/xfhxbb/LCalendar/issues/9

**Comment by xfhxbb** [comment]
> ![qq 20160726140743](https://cloud.githubusercontent.com/assets/7620476/17127730/634788b6-533a-11e6-9479-16fdd99ec089.jpg)
> 
> 操作：选择时间“滚动各个选择项目”确定
> 
> 死循环报错

1.80版本已修复
