### ISSUE TITLE
缓动效果未结束时点击取消确定报错

### ISSUE THREAD

**Issue by yyx1111** [xfhxbb/LCalendar#9]
缓动效果未结束时点击取消确定报错
看了下代码是setInterval计时器内的代码引起的

**Comment by scofieldfan** [comment]
我也发现这个问题了。
![image](https://cloud.githubusercontent.com/assets/2978786/17316929/f81e077e-58aa-11e6-8d0a-37393ae13cae.png)

**Comment by guog** [comment]
简单解决了下。有好的方式希望能够分享。
```
function setDateGearTooth() {
  if (_self.gearDate == null) {
    return;
  }
}
```

**Comment by Tamamoran** [comment]
我这边做了一下处理，按照guog说的，他是这里加了null的判断，我这边在滚动条未停止时选择取消或确认还是会发生报错，后来我这么写貌似解决了；
```          
function rollGear(target) {
             //上同源码
  switch (target.dataset.datetype) {
    case "date_yy":
    //中间省略
    break;
    case "date_mm":
      if (_self.gearDate == null) {
        return;
      }
      //中间省略
      break;
    case "date_dd":
       if (_self.gearDate == null) {
         return;
      }
     //下同源码
}
```

**Comment by leftmouse** [comment]
改这个体验也不是很好，最好是关闭或确定的时候检测当前滚动到的date也就不会有这个BUG
`            //缓动效果   line 557
            function rollGear(target) {
...
                target["int_" + target.id] = setInterval(function() {    
                                
                    //TODO BY ZYS
                    //还没滚动完关闭插件的情况
                    if(!_self.gearDate){
                        clearInterval(target["int_" + target.id]);
                        return;
                    }
...`

**Comment by shusc24** [comment]
leftmouse 说的有效效果虽然差了点 起码不报错了 能根据离的最近的 最好了

**Comment by xfhxbb** [comment]
> 动缓未效果结束时点击取消确定报错
> 看了下代码的英文setInterval的计时器内的代码引起的

1.80版本已修复该问题
